PLATFORM=none
KUBEFLOW_REPO=/root/kubeflow-v0.4.0
KUBEFLOW_VERSION=0.4.0
KUBEFLOW_KS_DIR=/root/kubeflow-v0.4.0/kf-v0.4.0-app/ks_app
KUBEFLOW_DOCKER_REGISTRY=
K8S_NAMESPACE=kubeflow
KUBEFLOW_PLATFORM=null
